# Generated by Django 5.1 on 2024-09-03 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_rename_author_comment_author_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='reply',
            name='author_email',
            field=models.EmailField(max_length=254),
        ),
    ]
