# Generated by Django 5.1 on 2024-09-04 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_comment_author_email_alter_reply_author_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='author_email',
            new_name='email',
        ),
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reply',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
